import { defineConfig } from 'vite';
import magicalSvg from "vite-plugin-magical-svg";
import fs from 'fs';
import { createHash } from 'crypto';

export default defineConfig(({ command }) => {

    // Prevent caching issues in production
    // xelis_playground_bg.wasm is wasm code generated by ./xelis_wasm.sh
    // xelis_playground.js is glue code generated by ./xelis_wasm.sh to load the wasm
    // It is set as external in the bundler to avoid minification and worker function linking issues
    // The function below is to hash the two files and append hash to force reload of browser caching if the code changes
    let xelis_playground_glue_hash = ``;
    let xelis_playground_glue_code = ``;
    let xelis_playground_wasm_hash = ``;
    if (command === `build`) {
        const glue_code = fs.readFileSync(`./public/xelis_playground.js`);
        xelis_playground_glue_hash = createHash(`sha256`).update(glue_code).digest(`hex`).slice(0, 8);
        xelis_playground_glue_code = glue_code.toString();

        const wasm_code = fs.readFileSync(`./public/xelis_playground_bg.wasm`);
        xelis_playground_wasm_hash = createHash(`sha256`).update(wasm_code).digest(`hex`).slice(0, 8);
    }

    /** @type {import('vite').UserConfig} */
    const config = {
        server: {
            headers: {
                "Cross-Origin-Opener-Policy": "same-origin",
                "Cross-Origin-Embedder-Policy": "require-corp"
            }
        },
        build: {
            assetsInlineLimit: Number.MAX_SAFE_INTEGER,
            rollupOptions: {
                external: (id, p, r) => {
                    if (id.includes(`/xelis_playground.js`)) {
                        return true;
                    }
                },
                output: {
                    paths: (id) => {
                        if (id.includes(`/xelis_playground.js`)) {
                            return `/xelis_playground_${xelis_playground_glue_hash}.js`;
                        }
                    },
                    manualChunks: (path) => {
                        if (path.includes("node_modules")) {
                            return 'vendor';
                        }

                        return null;
                    }
                }
            }
        },
        plugins: [
            magicalSvg({
                // By default, the output will be a dom element (the <svg> you can use inside the webpage).
                // You can also change the output to react (or any supported target) to get a component you can use.
                target: 'dom',

                // By default, the svgs are optimized with svgo. You can disable this by setting this to false.
                svgo: false,

                // By default, width and height set on SVGs are not preserved.
                // Set to true to preserve `width` and `height` on the generated SVG.
                preserveWidthHeight: false,

                // *Experimental* - set the width and height on generated SVGs.
                // If used with `preserveWidthHeight`, will only apply to SVGs without a width/height.
                //setWidthHeight: { width: '32', height: '32' },

                // *Experimental* - replace all instances of `fill="..."` and `stroke="..."`.
                // Set to `true` for 'currentColor`, or use a text value to set it to this value.
                // When enabled, use query param ?skip-recolor to not alter colors.
                // Disabled by default.
                setFillStrokeColor: true,

                // *Experimental* - if a SVG comes with `width` and `height` set but no `viewBox`,
                // assume the viewbox is `0 0 {width} {height}` and add it to the SVG.
                // Disabled by default.
                restoreMissingViewBox: true,
            }),
            {
                name: "bundle-end",
                closeBundle: () => {
                    if (command === `build`) {
                        xelis_playground_glue_code = xelis_playground_glue_code.replace(`xelis_playground_bg.wasm`, `xelis_playground_bg_${xelis_playground_wasm_hash}.wasm`);
                        fs.writeFileSync(`./dist/xelis_playground.js`, Buffer.from(xelis_playground_glue_code, `utf-8`));

                        fs.renameSync(`./dist/xelis_playground.js`, `./dist/xelis_playground_${xelis_playground_glue_hash}.js`);
                        fs.renameSync(`./dist/xelis_playground_bg.wasm`, `./dist/xelis_playground_bg_${xelis_playground_wasm_hash}.wasm`);
                    }
                }
            }
        ],
    }

    return config;
});
